version: '3.8'

services:
  app:
    image: bus-reservation:latest
    container_name: bus_app_prod
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql_prod:3306/busdb
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql_prod

  mysql_prod:
    image: mysql:8
    container_name: bus_db_prod
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: busdb
    ports:
      - "3308:3306"
